#!/bin/sh

# disable: VRR on games on X11, no transitions in bspwm
readonly ENABLE_COMPOSITOR="false"

nitrogen --restore
xrandr_setup.sh --toggle
sxhkd &
xsetroot -cursor_name left_ptr &
[[ "$ENABLE_COMPOSITOR" == "true" ]] && picom &
polybar_setup.sh
xfce4-clipman &
nm-applet &
# workaround to ensure audio is initialised
# pulseaudio -k

bspc monitor DisplayPort-0 -d 1 2 3 4
bspc monitor HDMI-A-0 -d 5 6 7 8

bspc config single_monocle      true
bspc config border_width        2
bspc config window_gap          6
bspc config focused_border_color "#5e81ac"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a clementine desktop='^8'
