= Custom Bash extensions

This repo contains several bash customizations for my personal use.

== Motivation (s)

. Make my installation of shells quicker
. Play a bit with Bash

== Installation

. Place the shell in the user home directory (type `cd`).

. Clone the repo with

 git clone https://github.com/abelsromero/bash-extensions.git ".${USER}_ext"

. Add the following lines to `.bashrc`, `.zshrc` or `.profile` depending on the setup.

 source ~/.${USER}_ext/bootstrap.sh

. Copy files in `home` folder to your home.

. Correct path to `.gitignore_global` in `.gitconfig`

. Set up your Git username and email.

 git config --global user.name "my.user@email.com"
 git config --global user.email "Name Surname(s)"

. Close and re-open the shell.

If all is fine, you should see the new shell layout.

== Plugins

A _plugin_ is any Bash script locating inside the 'plugins' directory inside the installation.
By default, any file with '.sh' extension in the 'plugins' folder will be automatically source.

== Tips & tricks

=== Hidden files

Files & folders can be named to avoid accidental commit.
Anything with prefix '_' will be ignored.
